let x = 80;
let y = 20;
let a = x + y;
let s = x - y;
let m = x * y;
let d = x / y;
let o = x % y;
let e = x ** y;

console.log('The value of x is : '+x);
console.log('The value of y is : '+y);
console.log();
console.log('Addition');
console.log('The Result is : '+a);
console.log();
console.log('Subtraction');
console.log('The Result is : '+s);
console.log();
console.log('Multiplication');
console.log('The Result is : '+m);
console.log();
console.log('Division');
console.log('The Result is : '+d);
console.log();
console.log('Modulus');
console.log('The Result is : '+o);
console.log();
console.log('Exponential');
console.log('The Result is : '+e);